### ISSUE TITLE
No licence file

### ISSUE THREAD

**Issue by tstibbs** [Aconex/scrutineer#17]
Scrutineer does not appear to have any licence information, but the readme appears to be encouraging users to download/build/run scrutineer.

This makes it very difficult for someone to use scrutineer, particularly in a commercial environment.

The [licensing page](https://help.github.com/articles/open-source-licensing) suggests adding a `licence.md` file containing the licence - AL2 would be great!

**Comment by tallpsmith** [comment]
Added LICENSE.md file via bab89d04d99e2041ff14a0f09cb248189e5360b4
