### ISSUE TITLE
Provide options to specify ES basic authentications to verify against secured ES Cluster 

### ISSUE THREAD

**Issue by rock-yu** [Aconex/scrutineer#38]
Use secured TransportClient if the following parameters are provided (ignore if esSecurityEnabled is not provided or set to false):
- esSecurityEnabled
- esUsername
- esPassword
- esSslEnabled
- esSslVerificationMode  (one of [none, certificate, full])

**Comment by tallpsmith** [comment]
Resolved as part of #47
