### ISSUE TITLE
Scrutineer stream comparison and event emission logic as a separate module

### ISSUE THREAD

**Issue by rock-yu** [Aconex/scrutineer#53]
**Is your feature request related to a problem? Please describe.**
We have a _verifier_ project which currently depend on `scrutineer.jar` to compare two streams of `ID:Version`, and we rely on `IdAndVersionStreamVerifierListener` to register our _handler_ to fix inconsistent records. However, our _verifier_ doesn't directly talk to `jdbc` or `Elastic search`, instead, it talks to various services via `HTTP` to get the list of `ID:Version`. We don't need those `jdbc/Elastic search` dependencies.

**Describe the solution you'd like**
We want a modularized `scrutineer` which separates the base `core/verifier` module and those plugin-like modules which implement different stream support (e.g: jdbc, Elastic search7, Open Search, solr etc)  

To maintain backward compatibility, we can leave the `com.aconex.scrutineer: scrutineer` maven artifact's dependencies as it is, which include `core`, `verifier`, `jdbc`, `Elastic search 7`, `command line runner` all together

**Describe alternatives you've considered**
I guess we can manually exclude those `Elastic Search 7` and `JDBC` dependencies from pom. 

**Additional context**
Just for the record, the followings are samples of our scrutineer integration code:

```
Collection<OurIDAndVersionStream> stream1 = httpClient1.fetchIdAndVersion(type = "SourceEntity", timestampSince = 0)

Collection<OurIDAndVersionStream> stream2 = httpClient2.fetchIdAndVersion(type = "TargetEntity", timestampSince = 0)

idAndVersionStreamVerifier.verify(stream1, stream2, ourIdAndVersionStreamVerifierListener)
```

**Comment by tallpsmith** [comment]
Note that I think this work will make #48  easier to implement too if I read the tea-leaves correctly.

**Comment by rock-yu** [comment]
Yes, Paul, that was part of the plan. I am also working on introducing a manifest-like configurations to run scrutineer, I will write the proposal  in another ticket

**Comment by tallpsmith** [comment]
Thanks, this has been merged.
