### ISSUE TITLE
Time to break away from ES-coupled release versions

### ISSUE THREAD

**Issue by rock-yu** [Aconex/scrutineer#65]
**Is your feature request related to a problem? Please describe.**
After recent restructuring, elasticsearch was reduced to a implementation module of a "connector", it's awkward to continue
coupling the release with elasticsearch version  

**Describe the solution you'd like**
What about releasing under artifactId "scrutineer2" and reset version in master

**Describe alternatives you've considered**
A new repo??

**Additional context**

**Comment by tallpsmith** [comment]
I have thought about a 2nd repo, but I think I'm going to just charge the `artifactId` to `scrutineer2`, and reset the version back to a `1.0.0`.  We can keep the child Connector module versions independent, perhaps matching their respective products version cycle?

**Comment by tallpsmith** [comment]
BTW, I'm working on a branch for this at the moment, let me know if you're also working in this area...

**Comment by tallpsmith** [comment]
Began a branch https://github.com/Aconex/scrutineer/tree/version_change

**Comment by tallpsmith** [comment]
Completed
