### ISSUE TITLE
EC2 discovery

### ISSUE THREAD

**Issue by achatzakis** [Aconex/scrutineer#9]
Hi and thanks for open sourcing such a useful tool!

Not sure if this is the correct channel to ask this, but we are trying to set this up and seems like it fails to detect our nodes.

We are using EC2 discovery, am I right that  scrutineer assumes a different discovery mode?
Is there a way to explicitly specify hostname/port of an elasticSearch node instead of relying on discovery based on cluster name?

thanks in advance!

**Comment by tallpsmith** [comment]
As ES's discovery methods have changed significantly over the years, I'm closing this issue.  Scrutineer now requires a least a set of seed nodes as part of initial configuration to be able to join the cluster.
